version: '3'
services:
  mysql:
    build: ./docker/mysql/
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: catapi
      MYSQL_USER: catapi
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
